// AUTO-GENERATED by scripts/elements-generate.ts — do not edit manually
// Run: make elements-generate
import type React from 'react';

export const CUSTOM_ELEMENT_REGISTRY: Record<
  string,
  () => Promise<{ default: React.ComponentType<{ data: any; style?: any; className?: string }> }>
> = {
  "countdown": () => import('./countdown.js'),
  "marquee": () => import('./marquee.js'),
  "marquee_slider": () => import('./marquee.js'),
  "accordion": () => import('./accordion.js'),
  "category_carousel": () => import('./category.js'),
  "categories": () => import('./category.js'),
  "collections": () => import('./category.js'),
  "gallery": () => import('./gallery.js'),
  "image_gallery": () => import('./gallery.js'),
  "imageGallery": () => import('./gallery.js'),
  "product_gallery": () => import('./gallery.js'),
  "productGallery": () => import('./gallery.js'),
  "html": () => import('./html.js'),
  "custom_html": () => import('./html.js'),
  "hero_slider": () => import('./hero_slider.js'),
  "hero": () => import('./hero_slider.js'),
  "custom_slider": () => import('./custom_carousel.js'),
  "customSlider": () => import('./custom_carousel.js'),
  "carousel": () => import('./image_carousel.js'),
  "imageCarousel": () => import('./image_carousel.js'),
  "product_carousel": () => import('./image_carousel.js'),
  "productCarousel": () => import('./image_carousel.js'),
  "list": () => import('./list.js'),
  "detail_list": () => import('./list_details.js'),
  "video_cards": () => import('./video_cards.js'),
  "boxes": () => import('./boxes.js'),
  "quotes": () => import('./quotes.js'),
  "testimonials": () => import('./quotes.js'),
  "testimonial": () => import('./quotes.js'),
  "sequence": () => import('./sequence.js'),
  "step": () => import('./steps.js'),
  "steps": () => import('./steps.js'),
};
